name: SecretSocietyOfTheNineUnknownMen
favicon: null
layout_spectrum: 0.64107
typography_spectrum: 1
title: Secret Society Of The Nine Unknown Men
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#fc8300'
    - '#ae3c00'
    - '#7d7366'
  brandStrength: 0
  lightness: 0.004089578753337264
  saturation: 0.5
  rhythmicContrast: 0.7264416986145079
purpose: []
